name: Deploy to GitHub Pages and Docker

on:
  push:
    branches:
      - main  # Adjust this if you want to deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust this based on your project's Node version

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: build  # The folder the action should deploy
          token: ${{ secrets.GITHUB_TOKEN }}  # Using the built-in GitHub Token
          clean: true
          force: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/magesgate-com:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # Adjust platforms as needed
          file: ./Dockerfile  # Path to your Dockerfile
